// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HtmlCategories() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container\"><h2 class=\"title text-center mb-4\">Explore Popular Categories</h2><!-- End .title text-center --><div class=\"cat-blocks-container\"><div class=\"row\"><div class=\"col-6 col-sm-4 col-lg-2\"></div><!-- End .col-sm-4 col-lg-2 --><div class=\"col-6 col-sm-4 col-lg-2\"><a href=\"category.html\" class=\"cat-block\"><figure><span><img src=\"/assets/images/demos/demo-4/cats/8.png\" alt=\"Category image\"></span></figure><h3 class=\"cat-block-title\">Fashion</h3><!-- End .cat-block-title --></a></div><!-- End .col-sm-4 col-lg-2 --><div class=\"col-6 col-sm-4 col-lg-2\"><a href=\"category.html\" class=\"cat-block\"><figure><span><img src=\"/assets/images/demos/demo-4/cats/3.png\" alt=\"Category image\"></span></figure><h3 class=\"cat-block-title\">Electronic</h3><!-- End .cat-block-title --></a></div><!-- End .col-sm-4 col-lg-2 --><div class=\"col-6 col-sm-4 col-lg-2\"><a href=\"category.html\" class=\"cat-block\"><figure><span><img src=\"/assets/images/demos/demo-4/cats/9.png\" alt=\"Category image\"></span></figure><h3 class=\"cat-block-title\">Motors</h3><!-- End .cat-block-title --></a></div><!-- End .col-sm-4 col-lg-2 --><div class=\"col-6 col-sm-4 col-lg-2\"><a href=\"category.html\" class=\"cat-block\"><figure><span><img src=\"/assets/images/demos/demo-4/cats/10.png\" alt=\"Category image\"></span></figure><h3 class=\"cat-block-title\">Sports</h3><!-- End .cat-block-title --></a></div><!-- End .col-sm-4 col-lg-2 --><div class=\"col-6 col-sm-4 col-lg-2\"></div><!-- End .col-sm-4 col-lg-2 --></div><!-- End .row --></div><!-- End .cat-blocks-container --></div><!-- End .container -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
