// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HtmlMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"header-bottom sticky-header\"><div class=\"container\"><div class=\"header-left\"></div><!-- End .header-left --><div class=\"header-center\"><nav class=\"main-nav\"><ul class=\"menu sf-arrows\"><li class=\"megamenu-container\"><a href=\"/\" class=\"\">Home</a></li><li><a href=\"/market\" class=\"\">Market</a></li><li><a href=\"/contact\" class=\"\">Contact</a></li><li><a href=\"/about\" class=\"\">About</a></li><li><a href=\"/faq\" class=\"\">FAQs</a></li></ul><!-- End .menu --></nav><!-- End .main-nav --></div><!-- End .header-center --><div class=\"header-right\"><i class=\"la la-lightbulb-o\"></i><p>Best deals<span class=\"highlight\">&nbsp;&nbsp;&nbsp;&nbsp;</span></p></div></div><!-- End .container --></div><!-- End .header-bottom -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
